FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN apk add --no-cache python3 make g++ 
RUN npm install

COPY . .

RUN npx tsc -p tsconfig.build.json

EXPOSE 3000

CMD ["npm", "run", "start:prod"]
